// All game content. Audio lives at audio/<grp>/<id>.mp3 (+ _slow variants).
// Every barrier word id has a matching hand-drawn <symbol id="pic-<id>"> in index.html.

const BARRIER_CATS = [
  {
    id: "animals", kn: "ಪ್ರಾಣಿಗಳು", en: "animals", icon: "naayi",
    items: [
      { id: "naayi",   kn: "ನಾಯಿ",    tr: "naayi",   en: "dog",      grp: "animals" },
      { id: "bekku",   kn: "ಬೆಕ್ಕು",   tr: "bekku",   en: "cat",      grp: "animals" },
      { id: "aane",    kn: "ಆನೆ",     tr: "aane",    en: "elephant", grp: "animals" },
      { id: "huli",    kn: "ಹುಲಿ",    tr: "huli",    en: "tiger",    grp: "animals" },
      { id: "hasu",    kn: "ಹಸು",     tr: "hasu",    en: "cow",      grp: "animals" },
      { id: "kudure",  kn: "ಕುದುರೆ",  tr: "kudure",  en: "horse",    grp: "animals" },
      { id: "meenu",   kn: "ಮೀನು",    tr: "meenu",   en: "fish",     grp: "animals" },
      { id: "hakki",   kn: "ಹಕ್ಕಿ",   tr: "hakki",   en: "bird",     grp: "animals" },
    ],
  },
  {
    id: "food", kn: "ತಿಂಡಿ ಊಟ", en: "food", icon: "dose",
    items: [
      { id: "anna_rice",  kn: "ಅನ್ನ",       tr: "anna",       en: "rice",   grp: "food" },
      { id: "haalu",      kn: "ಹಾಲು",      tr: "haalu",      en: "milk",   grp: "food" },
      { id: "neeru",      kn: "ನೀರು",      tr: "neeru",      en: "water",  grp: "food" },
      { id: "hannu",      kn: "ಹಣ್ಣು",     tr: "hannu",      en: "fruit",  grp: "food" },
      { id: "baalehannu", kn: "ಬಾಳೆಹಣ್ಣು", tr: "baalehannu", en: "banana", grp: "food" },
      { id: "dose",       kn: "ದೋಸೆ",      tr: "dose",       en: "dosa",   grp: "food" },
      { id: "mosaru",     kn: "ಮೊಸರು",     tr: "mosaru",     en: "curd",   grp: "food" },
      { id: "sihi",       kn: "ಸಿಹಿ",      tr: "sihi",      en: "sweet",  grp: "food" },
    ],
  },
  {
    id: "colors", kn: "ಬಣ್ಣಗಳು", en: "colors", icon: "kempu",
    items: [
      { id: "kempu",    kn: "ಕೆಂಪು",    tr: "kempu",    en: "red",    grp: "words" },
      { id: "hasiru",   kn: "ಹಸಿರು",    tr: "hasiru",   en: "green",  grp: "words" },
      { id: "neeli",    kn: "ನೀಲಿ",     tr: "neeli",    en: "blue",   grp: "words" },
      { id: "haladi",   kn: "ಹಳದಿ",     tr: "haladi",   en: "yellow", grp: "words" },
      { id: "bili",     kn: "ಬಿಳಿ",     tr: "bili",     en: "white",  grp: "words" },
      { id: "kappu",    kn: "ಕಪ್ಪು",    tr: "kappu",    en: "black",  grp: "words" },
      { id: "kittale",  kn: "ಕಿತ್ತಳೆ",  tr: "kittale",  en: "orange", grp: "words" },
      { id: "gulabi",   kn: "ಗುಲಾಬಿ",   tr: "gulabi",   en: "pink",   grp: "words" },
    ],
  },
  {
    id: "body", kn: "ಮೈ ಕೈ", en: "my body", icon: "kai",
    items: [
      { id: "kannu",  kn: "ಕಣ್ಣು",   tr: "kannu",  en: "eye",   grp: "words" },
      { id: "kivi",   kn: "ಕಿವಿ",    tr: "kivi",   en: "ear",   grp: "words" },
      { id: "moogu",  kn: "ಮೂಗು",    tr: "moogu",  en: "nose",  grp: "words" },
      { id: "baayi",  kn: "ಬಾಯಿ",    tr: "baayi",  en: "mouth", grp: "words" },
      { id: "kai",    kn: "ಕೈ",      tr: "kai",    en: "hand",  grp: "words" },
      { id: "kaalu",  kn: "ಕಾಲು",    tr: "kaalu",  en: "leg",   grp: "words" },
      { id: "tale",   kn: "ತಲೆ",     tr: "tale",   en: "head",  grp: "words" },
      { id: "hotte",  kn: "ಹೊಟ್ಟೆ",  tr: "hotte",  en: "tummy", grp: "words" },
    ],
  },
  {
    id: "home", kn: "ಮನೆಯಲ್ಲಿ", en: "at home", icon: "mane",
    items: [
      { id: "mane",    kn: "ಮನೆ",      tr: "mane",    en: "house",  grp: "words" },
      { id: "baagilu", kn: "ಬಾಗಿಲು",   tr: "baagilu", en: "door",   grp: "words" },
      { id: "kitaki",  kn: "ಕಿಟಕಿ",    tr: "kitaki",  en: "window", grp: "words" },
      { id: "kurchi",  kn: "ಕುರ್ಚಿ",   tr: "kurchi",  en: "chair",  grp: "words" },
      { id: "haasige", kn: "ಹಾಸಿಗೆ",   tr: "haasige", en: "bed",    grp: "words" },
      { id: "deepa",   kn: "ದೀಪ",      tr: "deepa",   en: "lamp",   grp: "words" },
      { id: "pustaka", kn: "ಪುಸ್ತಕ",   tr: "pustaka", en: "book",   grp: "words" },
      { id: "chendu",  kn: "ಚೆಂಡು",    tr: "chendu",  en: "ball",   grp: "words" },
    ],
  },
  {
    id: "actions", kn: "ಮಾಡೋಣ!", en: "action words", icon: "odu",
    items: [
      { id: "tinnu",  kn: "ತಿನ್ನು",  tr: "tinnu",  en: "eat",   grp: "words" },
      { id: "kudi",   kn: "ಕುಡಿ",    tr: "kudi",   en: "drink", grp: "words" },
      { id: "malagu", kn: "ಮಲಗು",    tr: "malagu", en: "sleep", grp: "words" },
      { id: "odu",    kn: "ಓಡು",     tr: "odu",    en: "run",   grp: "words" },
      { id: "nagu",   kn: "ನಗು",     tr: "nagu",   en: "laugh", grp: "words" },
      { id: "alu",    kn: "ಅಳು",     tr: "alu",    en: "cry",   grp: "words" },
      { id: "kuni",   kn: "ಕುಣಿ",    tr: "kuni",   en: "dance", grp: "words" },
      { id: "jigi",   kn: "ಜಿಗಿ",    tr: "jigi",   en: "jump",  grp: "words" },
    ],
  },
];

const MISSIONS = [
  // tier 1 — single phrases
  { id: "m_neeru",     tier: 1, do: "Ask for water — in Kannada only!",            kn: "ನೀರು ಬೇಕು",                        tr: "neeru beku" },
  { id: "m_hasivu",    tier: 1, do: "Tell someone you're hungry",                  kn: "ನನಗೆ ಹಸಿವು",                       tr: "nanage hasivu" },
  { id: "m_baa",       tier: 1, do: "Call someone over to you",                    kn: "ಬಾ ಇಲ್ಲಿ",                          tr: "baa illi" },
  { id: "m_beda",      tier: 1, do: "Say no-thanks to something, the Kannada way", kn: "ಬೇಡ",                              tr: "beda" },
  { id: "m_innu",      tier: 1, do: "Ask for more of something you like",          kn: "ಇನ್ನೂ ಬೇಕು",                       tr: "innu beku" },
  { id: "m_hogona",    tier: 1, do: "Time to leave? You say it first",             kn: "ಹೋಗೋಣ!",                           tr: "hogona" },
  { id: "m_chennagide",tier: 1, do: "Say something is really nice",                kn: "ಚೆನ್ನಾಗಿದೆ!",                      tr: "chennagide" },
  { id: "m_goodnight", tier: 1, do: "Say good night in Kannada tonight",           kn: "ಶುಭರಾತ್ರಿ",                        tr: "shubharaatri" },
  { id: "m_thanks",    tier: 1, do: "Say thank you in Kannada today",              kn: "ಧನ್ಯವಾದ",                          tr: "dhanyavaada" },
  { id: "m_bartini",   tier: 1, do: "When someone calls you, answer in Kannada",   kn: "ಬರ್ತೀನಿ!",                         tr: "bartini" },
  { id: "m_appa_elli", tier: 1, do: "Ask where appa (or amma) is",                 kn: "ಅಪ್ಪ ಎಲ್ಲಿ?",                      tr: "appa elli" },
  { id: "m_elu",       tier: 1, do: "Wake somebody up — loudly!",                  kn: "ಏಳು!",                             tr: "elu" },
  { id: "m_banni",     tier: 1, do: "Call everyone to the table",                  kn: "ಊಟಕ್ಕೆ ಬನ್ನಿ!",                    tr: "ootakke banni" },
  { id: "m_gottilla",  tier: 1, do: "Don't know the answer? Say so in Kannada",    kn: "ಗೊತ್ತಿಲ್ಲ",                        tr: "gottilla" },
  { id: "m_saaku",     tier: 1, do: "Had enough of something? Say it",             kn: "ಸಾಕು!",                            tr: "saaku" },
  { id: "m_adu_beku",  tier: 1, do: "Point at something you want and ask",         kn: "ಅದು ಬೇಕು",                         tr: "adu beku" },
  { id: "m_yaaru",     tier: 1, do: "Someone at the door? Ask who it is",          kn: "ಯಾರು?",                            tr: "yaaru" },
  { id: "m_elli_ide",  tier: 1, do: "Lost something? Ask where it is",             kn: "ಎಲ್ಲಿ ಇದೆ?",                       tr: "elli ide" },
  { id: "m_idu_nodu",  tier: 1, do: "Show someone something cool",                 kn: "ಇದು ನೋಡು!",                        tr: "idu nodu" },
  { id: "m_idu_ishta", tier: 1, do: "Tell the cook you like this food",            kn: "ನನಗೆ ಇದು ಇಷ್ಟ",                    tr: "nanage idu ishta" },
  { id: "m_baagilu",   tier: 1, do: "Ask someone to open the door",                kn: "ಬಾಗಿಲು ತೆಗಿ",                      tr: "baagilu tegi" },
  { id: "m_innondu",   tier: 1, do: "Ask for one more — of anything!",             kn: "ಇನ್ನೂ ಒಂದು!",                      tr: "innu ondu" },
  // tier 2 — sentences
  { id: "m_ootakke",   tier: 2, do: "Ask what's for dinner",                       kn: "ಊಟಕ್ಕೆ ಏನು?",                      tr: "ootakke enu" },
  { id: "m_ruchi",     tier: 2, do: "Tell the cook the food is tasty",             kn: "ತುಂಬಾ ರುಚಿ ಇದೆ!",                  tr: "tumba ruchi ide" },
  { id: "m_horage",    tier: 2, do: "Ask if you can go outside",                   kn: "ಹೊರಗೆ ಹೋಗಲಾ?",                     tr: "horage hogala" },
  { id: "m_sahaaya",   tier: 2, do: "Ask someone for a little help",               kn: "ಸ್ವಲ್ಪ ಸಹಾಯ ಮಾಡು",                 tr: "svalpa sahaaya maadu" },
  { id: "m_count5",    tier: 2, do: "Count something out loud to five",            kn: "ಒಂದು, ಎರಡು, ಮೂರು, ನಾಲ್ಕು, ಐದು",     tr: "ondu, eradu, mooru, naalku, aidu" },
  { id: "m_love",      tier: 2, do: "Tell amma you love her — in Kannada",         kn: "ಅಮ್ಮ, ನೀನು ಅಂದ್ರೆ ನನಗೆ ಇಷ್ಟ",       tr: "amma, neenu andre nanage ishta" },
  { id: "m_nidde",     tier: 2, do: "Tell someone you're getting sleepy",          kn: "ನನಗೆ ನಿದ್ದೆ ಬರ್ತಿದೆ",              tr: "nanage nidde bartide" },
  { id: "m_jote_aata", tier: 2, do: "Invite someone to play with you",             kn: "ನನ್ನ ಜೊತೆ ಆಟ ಆಡ್ತೀಯಾ?",             tr: "nanna jote aata aadtiya?" },
  { id: "m_tv",        tier: 2, do: "Ask permission to watch TV",                  kn: "ಟಿವಿ ನೋಡಲಾ?",                      tr: "TV nodala?" },
  { id: "m_dress",     tier: 2, do: "Give someone a compliment",                   kn: "ನಿನ್ನ ಡ್ರೆಸ್ ಚೆನ್ನಾಗಿದೆ!",          tr: "ninna dress chennagide!" },
  { id: "m_hege",      tier: 2, do: "Ask how something is done",                   kn: "ಇದು ಹೇಗೆ ಮಾಡೋದು?",                 tr: "idu hege maadodu?" },
  { id: "m_enaaytu",   tier: 2, do: "Someone looks sad — ask what happened",       kn: "ಏನಾಯ್ತು?",                         tr: "enaaytu?" },
  { id: "m_light",     tier: 2, do: "Ask someone to switch off the light",         kn: "ಲೈಟ್ ಆಫ್ ಮಾಡು",                    tr: "light off maadu" },
  { id: "m_kai_tole",  tier: 2, do: "Announce you washed your hands",              kn: "ನಾನು ಕೈ ತೊಳೆದೆ!",                  tr: "naanu kai tolede!" },
  { id: "m_hallu",     tier: 2, do: "Announce you brushed your teeth",             kn: "ನಾನು ಹಲ್ಲು ಉಜ್ಜಿದೆ!",              tr: "naanu hallu ujjide!" },
  // tier 3 — negotiation & open speech
  { id: "m_screentime",tier: 3, do: "Negotiate ten more minutes of screen time — Kannada only", kn: "ಇನ್ನೂ ಹತ್ತು ನಿಮಿಷ ಪ್ಲೀಸ್!", tr: "innu hattu nimisha please" },
  { id: "m_school",    tier: 3, do: "Tell one thing about your day — start like this and finish it yourself", kn: "ಇವತ್ತು ಶಾಲೆಯಲ್ಲಿ…", tr: "ivattu shaaleyalli…" },
  { id: "m_tindi",     tier: 3, do: "Ask for your snack with a full sentence",     kn: "ಅಮ್ಮ, ನನಗೆ ತಿಂಡಿ ಕೊಡು",             tr: "amma, nanage tindi kodu" },
  { id: "m_3fruits",   tier: 3, do: "Name three fruits out loud in the kitchen",   kn: "ಬಾಳೆಹಣ್ಣು, ಕಿತ್ತಳೆ, ಸೇಬು!",         tr: "baalehannu, kittale, sebu!" },
  { id: "m_favfood",   tier: 3, do: "Say your favourite food in a full sentence — swap in your own!", kn: "ನನಗೆ ದೋಸೆ ತುಂಬಾ ಇಷ್ಟ", tr: "nanage dose tumba ishta" },
  { id: "m_kanasu",    tier: 3, do: "Invent a silly dream and tell it",            kn: "ಇವತ್ತು ಕನಸಲ್ಲಿ ಒಂದು ಆನೆ ಬಂತು!",     tr: "ivattu kanasalli ondu aane bantu!" },
  { id: "m_secret",    tier: 3, do: "Tell your sibling a secret — in Kannada",     kn: "ನಿನಗೊಂದು ಸೀಕ್ರೆಟ್ ಹೇಳ್ತೀನಿ",        tr: "ninagondu secret heltini" },
  { id: "m_count10",   tier: 3, do: "Count all the way to ten!",                   kn: "ಒಂದು, ಎರಡು, ಮೂರು, ನಾಲ್ಕು, ಐದು, ಆರು, ಏಳು, ಎಂಟು, ಒಂಬತ್ತು, ಹತ್ತು", tr: "ondu … hattu" },
];

const ECHO = [
  // level 1 — little words
  { id: "e_neeru",   lvl: 1, kn: "ನೀರು ಬೇಕು",            tr: "neeru beku" },
  { id: "e_baa",     lvl: 1, kn: "ಬಾ ಇಲ್ಲಿ",              tr: "baa illi" },
  { id: "e_amma",    lvl: 1, kn: "ಅಮ್ಮ ಎಲ್ಲಿ?",           tr: "amma elli?" },
  { id: "e_naayi",   lvl: 1, kn: "ನಾಯಿ ನೋಡು!",            tr: "naayi nodu!" },
  { id: "e_bekku",   lvl: 1, kn: "ಅದು ಬೆಕ್ಕು",            tr: "adu bekku" },
  { id: "e_ishta",   lvl: 1, kn: "ನನಗೆ ಇಷ್ಟ",             tr: "nanage ishta" },
  { id: "e_chenna",  lvl: 1, kn: "ತುಂಬಾ ಚೆನ್ನ",           tr: "tumba chenna" },
  { id: "e_bega",    lvl: 1, kn: "ಬೇಗ ಬಾ",               tr: "bega baa" },
  { id: "e_svalpa",  lvl: 1, kn: "ಇನ್ನೂ ಸ್ವಲ್ಪ",          tr: "innu svalpa" },
  { id: "e_hotte",   lvl: 1, kn: "ಹೊಟ್ಟೆ ತುಂಬಿತು",        tr: "hotte tumbitu" },
  { id: "e_kai",     lvl: 1, kn: "ಕೈ ಕೊಡು",              tr: "kai kodu" },
  { id: "e_mele",    lvl: 1, kn: "ಮೇಲೆ ನೋಡು",            tr: "mele nodu" },
  { id: "e_olage",   lvl: 1, kn: "ಒಳಗೆ ಬಾ",              tr: "olage baa" },
  { id: "e_gottaytu",lvl: 1, kn: "ಗೊತ್ತಾಯ್ತು!",           tr: "gottaaytu!" },
  { id: "e_nodu_adu",lvl: 1, kn: "ಅದು ನೋಡು",             tr: "adu nodu" },
  // level 2 — sentences
  { id: "e_dose",    lvl: 2, kn: "ನನಗೆ ದೋಸೆ ಬೇಕು",                tr: "nanage dose beku" },
  { id: "e_haalu",   lvl: 2, kn: "ಬೆಕ್ಕು ಹಾಲು ಕುಡಿಯುತ್ತೆ",         tr: "bekku haalu kudiyutte" },
  { id: "e_aane",    lvl: 2, kn: "ಆನೆ ತುಂಬಾ ದೊಡ್ಡದು",              tr: "aane tumba doddadu" },
  { id: "e_shaale",  lvl: 2, kn: "ಇವತ್ತು ಶಾಲೆ ಇಲ್ಲ",               tr: "ivattu shaale illa" },
  { id: "e_huli",    lvl: 2, kn: "ಹುಲಿ ಕಾಡಲ್ಲಿ ಇರುತ್ತೆ",           tr: "huli kaadalli irutte" },
  { id: "e_oota",    lvl: 2, kn: "ನಾನು ಊಟ ಮಾಡಿದೆ",                tr: "naanu oota maadide" },
  { id: "e_joraagi", lvl: 2, kn: "ನಾಯಿ ಜೋರಾಗಿ ಬೊಗಳುತ್ತೆ",          tr: "naayi joraagi bogalutte" },
  { id: "e_kodu",    lvl: 2, kn: "ನನಗೆ ಸ್ವಲ್ಪ ನೀರು ಕೊಡು",          tr: "nanage svalpa neeru kodu" },
  { id: "e_male",    lvl: 2, kn: "ಇವತ್ತು ಮಳೆ ಬರುತ್ತೆ",             tr: "ivattu male barutte" },
  { id: "e_mara",    lvl: 2, kn: "ಹಕ್ಕಿ ಮರದ ಮೇಲೆ ಇದೆ",             tr: "hakki marada mele ide" },
  { id: "e_chendu",  lvl: 2, kn: "ನಾನು ಚೆಂಡು ಆಡ್ತೀನಿ",             tr: "naanu chendu aadtini" },
  { id: "e_ajji_oota",lvl: 2, kn: "ಅಜ್ಜಿ ಊಟ ಮಾಡ್ತಿದ್ದಾರೆ",         tr: "ajji oota maadtiddaare" },
  { id: "e_tolede",  lvl: 2, kn: "ನಾನು ಕೈ ತೊಳೆದೆ",                tr: "naanu kai tolede" },
  { id: "e_belagge", lvl: 2, kn: "ಬೆಳಗ್ಗೆ ಹಾಲು ಕುಡಿದೆ",            tr: "belagge haalu kudide" },
  { id: "e_chikkadu",lvl: 2, kn: "ನಮ್ಮ ಮನೆ ಚಿಕ್ಕದು",              tr: "namma mane chikkadu" },
  // level 3 — big-kid talk
  { id: "e_anna",    lvl: 3, kn: "ಅಮ್ಮ, ನನಗೆ ಇನ್ನೂ ಸ್ವಲ್ಪ ಅನ್ನ ಬೇಕು", tr: "amma, nanage innu svalpa anna beku" },
  { id: "e_park",    lvl: 3, kn: "ನಾವು ಪಾರ್ಕ್‌ಗೆ ಹೋಗೋಣವಾ?",        tr: "naavu park-ge hogonavaa?" },
  { id: "e_ajji",    lvl: 3, kn: "ಅಜ್ಜಿ ಮನೆಗೆ ಯಾವಾಗ ಹೋಗ್ತೀವಿ?",     tr: "ajji manege yaavaaga hogtivi?" },
  { id: "e_kannada", lvl: 3, kn: "ನನಗೆ ಕನ್ನಡ ಮಾತಾಡೋಕೆ ಇಷ್ಟ",        tr: "nanage kannada maataadoke ishta" },
  { id: "e_nidde",   lvl: 3, kn: "ನನಗೆ ತುಂಬಾ ನಿದ್ದೆ ಬರ್ತಿದೆ",        tr: "nanage tumba nidde bartide" },
  { id: "e_naale",   lvl: 3, kn: "ನಾಳೆ ನಾವು ಏನು ಮಾಡೋಣ?",           tr: "naale naavu enu maadona?" },
  { id: "e_eeju",    lvl: 3, kn: "ನಾಳೆ ನಾವು ಈಜಲು ಹೋಗೋಣವಾ?",        tr: "naale naavu eejalu hogonavaa?" },
  { id: "e_kathe",   lvl: 3, kn: "ನನಗೆ ಒಂದು ಕಥೆ ಹೇಳ್ತೀಯಾ?",         tr: "nanage ondu kathe heltiyaa?" },
  { id: "e_office",  lvl: 3, kn: "ಅಪ್ಪ ಆಫೀಸ್‌ನಿಂದ ಯಾವಾಗ ಬರ್ತಾರೆ?",   tr: "appa office-inda yaavaaga bartaare?" },
  { id: "e_pilot",   lvl: 3, kn: "ನಾನು ದೊಡ್ಡವನಾದ ಮೇಲೆ ಪೈಲಟ್ ಆಗ್ತೀನಿ", tr: "naanu doddavanaada mele pilot aagtini" },
  { id: "e_aduge",   lvl: 3, kn: "ಇವತ್ತು ರಾತ್ರಿ ಏನು ಅಡುಗೆ?",         tr: "ivattu raatri enu aduge?" },
  { id: "e_kalisu",  lvl: 3, kn: "ನನ್ನ ಸ್ನೇಹಿತನಿಗೆ ಕನ್ನಡ ಕಲಿಸ್ತೀನಿ",  tr: "nanna snehitanige kannada kalistini" },
  { id: "e_male_ninta",lvl: 3, kn: "ಮಳೆ ನಿಂತ ಮೇಲೆ ಹೊರಗೆ ಹೋಗೋಣ",     tr: "male ninta mele horage hogona" },
  { id: "e_best_dose",lvl: 3, kn: "ಅಜ್ಜಿ ಮಾಡಿದ ದೋಸೆ ಪ್ರಪಂಚದಲ್ಲೇ ಬೆಸ್ಟ್", tr: "ajji maadida dose prapanchadalle best" },
  { id: "e_khushi",  lvl: 3, kn: "ನನಗೆ ಇವತ್ತು ತುಂಬಾ ಖುಷಿ ಆಗಿದೆ",     tr: "nanage ivattu tumba khushi aagide" },
];

const AJJI_PACKS = [
  {
    id: "basics", title: "hello ajji!",
    items: [
      { id: "a_hegiddiya",  kn: "ಅಜ್ಜಿ, ಹೇಗಿದ್ದೀಯಾ?",     tr: "ajji, hegiddiya?",       en: "Ajji, how are you?" },
      { id: "a_chennagi",   kn: "ನಾನು ಚೆನ್ನಾಗಿದ್ದೀನಿ!",   tr: "naanu chennagiddini!",   en: "I'm doing great!" },
      { id: "a_oota",       kn: "ಊಟ ಆಯ್ತಾ?",              tr: "oota aayta?",            en: "Did you eat?" },
      { id: "a_enu_maadide",kn: "ಇವತ್ತು ಏನು ಮಾಡಿದೆ?",     tr: "ivattu enu maadide?",    en: "What did you do today?" },
      { id: "a_bye",        kn: "ಮತ್ತೆ ಮಾತಾಡೋಣ, ಬೈ!",     tr: "matte maataadona, bye!", en: "Let's talk again, bye!" },
    ],
  },
  {
    id: "school", title: "school & play",
    items: [
      { id: "a_shaalege",   kn: "ನಾನು ಶಾಲೆಗೆ ಹೋದೆ",              tr: "naanu shaalege hode",           en: "I went to school" },
      { id: "a_friend",     kn: "ನನ್ನ ಫ್ರೆಂಡ್ ಜೊತೆ ಆಡಿದೆ",         tr: "nanna friend jote aadide",      en: "I played with my friend" },
      { id: "a_kalite",     kn: "ಇವತ್ತು ಏನು ಕಲಿತೆ ಗೊತ್ತಾ?",        tr: "ivattu enu kalite gotta?",      en: "Know what I learnt today?" },
      { id: "a_chikkavalu", kn: "ನೀನು ಚಿಕ್ಕವಳಿದ್ದಾಗ ಹೇಗಿತ್ತು?",     tr: "neenu chikkavaliddaaga hegittu?", en: "What was it like when you were little?" },
      { id: "a_nenapu",     kn: "ನಿನ್ನ ನೆನಪು ಆಗ್ತಿದೆ",             tr: "ninna nenapu aagtide",          en: "I miss you" },
    ],
  },
  {
    id: "food", title: "food talk",
    items: [
      { id: "a_aduge",      kn: "ಇವತ್ತು ಏನು ಅಡುಗೆ ಮಾಡಿದೆ?",        tr: "ivattu enu aduge maadide?",     en: "What did you cook today?" },
      { id: "a_dose_tinde", kn: "ನಾನು ದೋಸೆ ತಿಂದೆ",                tr: "naanu dose tinde",              en: "I ate dosa" },
      { id: "a_best_cook",  kn: "ನಿನ್ನ ಕೈ ಅಡುಗೆ ಬೆಸ್ಟ್!",           tr: "ninna kai aduge best!",         en: "Your cooking is the best!" },
      { id: "a_laadu",      kn: "ನನಗೆ ಲಾಡು ಮಾಡಿಕೊಡ್ತೀಯಾ?",         tr: "nanage laadu maadikodtiyaa?",   en: "Will you make me laddu?" },
      { id: "a_bega_baa",   kn: "ಬೇಗ ಬಾ ಅಜ್ಜಿ!",                  tr: "bega baa ajji!",                en: "Come soon, ajji!" },
    ],
  },
  {
    id: "questions", title: "big questions",
    items: [
      { id: "a_ajja",       kn: "ಅಜ್ಜ ಹೇಗಿದ್ದಾರೆ?",               tr: "ajja hegiddaare?",              en: "How is ajja?" },
      { id: "a_male",       kn: "ಅಲ್ಲಿ ಮಳೆ ಬರ್ತಿದೆಯಾ?",            tr: "alli male bartideyaa?",         en: "Is it raining there?" },
      { id: "a_enu_madtiya",kn: "ನೀನು ಏನು ಮಾಡ್ತಿದ್ದೀಯಾ?",          tr: "neenu enu maadtiddiyaa?",       en: "What are you doing?" },
      { id: "a_kathe",      kn: "ಒಂದು ಕಥೆ ಹೇಳು ಅಜ್ಜಿ",            tr: "ondu kathe helu ajji",          en: "Tell me a story, ajji" },
      { id: "a_india",      kn: "ನಾನು ಇಂಡಿಯಾಗೆ ಬರ್ತೀನಿ!",          tr: "naanu india-ge bartini!",       en: "I'm coming to India!" },
    ],
  },
];

const STORIES = [
  {
    id: "hasida_bekku", title_kn: "ಹಸಿದ ಬೆಕ್ಕು", title_en: "The Hungry Cat", icon: "bekku",
    parts: [
      { type: "line", id: "s_1",  kn: "ಒಂದು ಊರಲ್ಲಿ ಒಂದು ಬೆಕ್ಕು ಇತ್ತು.",          en: "In a little town there was a cat.",      art: "bekku" },
      { type: "line", id: "s_2",  kn: "ಬೆಕ್ಕಿಗೆ ತುಂಬಾ ಹಸಿವು!",                    en: "The cat was very hungry!",               art: "bekku" },
      { type: "line", id: "s_3",  kn: "ಬೆಕ್ಕು ಒಂದು ಮನೆಗೆ ಹೋಯಿತು.",               en: "The cat went to a house.",               art: "mane" },
      { type: "line", id: "s_4",  kn: "ಅಲ್ಲಿ ಒಂದು ದೊಡ್ಡ ದೋಸೆ ಇತ್ತು!",              en: "There was a big dosa there!",            art: "dose" },
      { type: "q",    id: "sq_1", kn: "ಮನೆಯಲ್ಲಿ ಏನು ಇತ್ತು — ದೋಸೆನಾ, ಬಾಳೆಹಣ್ಣಾ?",   opts: ["dose", "baalehannu"], ans: "dose" },
      { type: "line", id: "s_5",  kn: "ಆದರೆ ಅಲ್ಲಿ ಒಂದು ನಾಯಿ ಇತ್ತು.",              en: "But there was a dog there.",             art: "naayi" },
      { type: "q",    id: "sq_2", kn: "ಅಲ್ಲಿ ಯಾರು ಇತ್ತು — ನಾಯಿನಾ, ಹುಲಿನಾ?",        opts: ["naayi", "huli"], ans: "naayi" },
      { type: "line", id: "s_6",  kn: "ನಾಯಿ ಹೇಳಿತು: “ಬೌ ಬೌ! ಇದು ನನ್ನ ದೋಸೆ!”", en: "The dog said: Bow bow! This is my dosa!", art: "naayi" },
      { type: "line", id: "s_7",  kn: "ಬೆಕ್ಕು ಹೇಳಿತು: “ಮಿಯಾಂವ್! ನನಗೆ ತುಂಬಾ ಹಸಿವು!”", en: "The cat said: Miaow! I'm so hungry!", art: "bekku" },
      { type: "q",    id: "sq_3", kn: "ಯಾರಿಗೆ ಹಸಿವು — ಬೆಕ್ಕಿಗಾ, ಆನೆಗಾ?",           opts: ["bekku", "aane"], ans: "bekku" },
      { type: "line", id: "s_8",  kn: "ನಾಯಿ ಒಳ್ಳೆಯದು. ಅರ್ಧ ದೋಸೆ ಕೊಟ್ಟಿತು.",        en: "The dog was kind. It gave half the dosa.", art: "dose" },
      { type: "line", id: "s_9",  kn: "ಇಬ್ಬರೂ ದೋಸೆ ತಿಂದರು.",                      en: "They both ate the dosa.",                art: "tinnu" },
      { type: "line", id: "s_10", kn: "ಬೆಕ್ಕು ಮತ್ತು ನಾಯಿ ಫ್ರೆಂಡ್ಸ್ ಆದರು!",         en: "The cat and the dog became friends!",    art: "nagu" },
      { type: "q",    id: "sq_4", kn: "ಇಬ್ಬರೂ ಏನು ತಿಂದರು — ದೋಸೆನಾ, ಮೀನಾ?",         opts: ["dose", "meenu"], ans: "dose" },
    ],
  },
  {
    id: "aane_hakki", title_kn: "ದೊಡ್ಡ ಆನೆ, ಚಿಕ್ಕ ಹಕ್ಕಿ", title_en: "Big Elephant, Little Bird", icon: "aane",
    parts: [
      { type: "line", id: "t_1",  kn: "ಕಾಡಲ್ಲಿ ಒಂದು ದೊಡ್ಡ ಆನೆ ಇತ್ತು.",            en: "In the forest there was a big elephant.", art: "aane" },
      { type: "line", id: "t_2",  kn: "ಮರದ ಮೇಲೆ ಒಂದು ಚಿಕ್ಕ ಹಕ್ಕಿ ಇತ್ತು.",          en: "On a tree there was a little bird.",      art: "hakki" },
      { type: "line", id: "t_3",  kn: "ಆನೆಗೆ ತುಂಬಾ ಬಾಯಾರಿಕೆ — ನೀರು ಬೇಕು!",         en: "The elephant was so thirsty — it needed water!", art: "neeru" },
      { type: "q",    id: "tq_1", kn: "ಆನೆಗೆ ಏನು ಬೇಕು — ನೀರಾ, ಹಾಲಾ?",              opts: ["neeru", "haalu"], ans: "neeru" },
      { type: "line", id: "t_4",  kn: "ಆದರೆ ನೀರು ಎಲ್ಲಿ ಇದೆ? ಆನೆಗೆ ಗೊತ್ತಿಲ್ಲ.",      en: "But where was the water? The elephant didn't know.", art: "aane" },
      { type: "line", id: "t_5",  kn: "ಹಕ್ಕಿ ಹೇಳಿತು: “ಬಾ, ನಾನು ತೋರಿಸ್ತೀನಿ!”",   en: "The bird said: Come, I'll show you!",     art: "hakki" },
      { type: "line", id: "t_6",  kn: "ಹಕ್ಕಿ ಹಾರಿತು, ಆನೆ ನಡೆಯಿತು.",               en: "The bird flew, the elephant walked.",     art: "hakki" },
      { type: "q",    id: "tq_2", kn: "ಯಾರು ಹಾರಿತು — ಹಕ್ಕಿನಾ, ಹಸುನಾ?",             opts: ["hakki", "hasu"], ans: "hakki" },
      { type: "line", id: "t_7",  kn: "ಅಲ್ಲಿ ಒಂದು ದೊಡ್ಡ ಕೆರೆ ಇತ್ತು!",              en: "There was a big lake!",                   art: "neeru" },
      { type: "line", id: "t_8",  kn: "ಆನೆ ನೀರು ಕುಡಿಯಿತು. ತುಂಬಾ ಖುಷಿ!",           en: "The elephant drank. So happy!",           art: "kudi" },
      { type: "line", id: "t_9",  kn: "ದೊಡ್ಡ ಆನೆಗೆ ಚಿಕ್ಕ ಹಕ್ಕಿ ಸಹಾಯ ಮಾಡಿತು!",      en: "The little bird helped the big elephant!", art: "hakki" },
      { type: "q",    id: "tq_3", kn: "ಯಾರು ಸಹಾಯ ಮಾಡಿತು — ಹಕ್ಕಿನಾ, ಹುಲಿನಾ?",       opts: ["hakki", "huli"], ans: "hakki" },
    ],
  },
  {
    id: "hasu_haalu", title_kn: "ಹಸು ಮತ್ತು ಹಾಲು", title_en: "The Cow and the Milk", icon: "hasu",
    parts: [
      { type: "line", id: "u_1",  kn: "ಬೆಳಗ್ಗೆ ಆಯ್ತು. ಸೂರ್ಯ ಬಂದ!",                en: "Morning came. The sun came up!",          art: "haladi" },
      { type: "line", id: "u_2",  kn: "ಪುಟ್ಟ ಹುಡುಗ ಎದ್ದ: “ನನಗೆ ಹಾಲು ಬೇಕು!”",    en: "A little boy woke up: I want milk!",      art: "haalu" },
      { type: "line", id: "u_3",  kn: "ಆದರೆ ಮನೆಯಲ್ಲಿ ಹಾಲು ಇಲ್ಲ!",                 en: "But there was no milk at home!",          art: "mane" },
      { type: "q",    id: "uq_1", kn: "ಮನೆಯಲ್ಲಿ ಏನು ಇಲ್ಲ — ಹಾಲಾ, ನೀರಾ?",           opts: ["haalu", "neeru"], ans: "haalu" },
      { type: "line", id: "u_4",  kn: "ಅಮ್ಮ ಹೇಳಿದರು: “ಹಸು ಹತ್ತಿರ ಹೋಗೋಣ.”",      en: "Amma said: Let's go to the cow.",         art: "hasu" },
      { type: "line", id: "u_5",  kn: "ಹಸು ಹೇಳಿತು: “ಅಂಬಾ!”",                   en: "The cow said: Ambaa!",                    art: "hasu" },
      { type: "line", id: "u_6",  kn: "ಹಸು ಹಾಲು ಕೊಟ್ಟಿತು.",                      en: "The cow gave milk.",                      art: "haalu" },
      { type: "q",    id: "uq_2", kn: "ಹಾಲು ಯಾರು ಕೊಟ್ಟಿತು — ಹಸುನಾ, ಕುದುರೆನಾ?",     opts: ["hasu", "kudure"], ans: "hasu" },
      { type: "line", id: "u_7",  kn: "ಹುಡುಗ ಹಾಲು ಕುಡಿದ: “ಥ್ಯಾಂಕ್ಸ್, ಹಸು!”",    en: "The boy drank the milk: Thanks, cow!",    art: "kudi" },
      { type: "line", id: "u_8",  kn: "ಹುಡುಗ ಹಸುಗೆ ಒಂದು ಬಾಳೆಹಣ್ಣು ಕೊಟ್ಟ!",        en: "The boy gave the cow a banana!",          art: "baalehannu" },
      { type: "q",    id: "uq_3", kn: "ಹಸುಗೆ ಏನು ಕೊಟ್ಟ — ಬಾಳೆಹಣ್ಣಾ, ಮೀನಾ?",        opts: ["baalehannu", "meenu"], ans: "baalehannu" },
    ],
  },
  {
    id: "kempu_chendu", title_kn: "ಕೆಂಪು ಚೆಂಡು", title_en: "The Red Ball", icon: "chendu",
    parts: [
      { type: "line", id: "v_1",  kn: "ಒಬ್ಬ ಹುಡುಗನ ಹತ್ತಿರ ಒಂದು ಕೆಂಪು ಚೆಂಡು ಇತ್ತು.", en: "A boy had a red ball.",                 art: "chendu" },
      { type: "line", id: "v_2",  kn: "ಚೆಂಡು ಪುಟ್ಟ ಪುಟ್ಟ ಜಿಗಿಯಿತು!",              en: "The ball bounced and bounced!",           art: "jigi" },
      { type: "line", id: "v_3",  kn: "ಚೆಂಡು ಕಿಟಕಿಯಿಂದ ಹೊರಗೆ ಹೋಯಿತು!",            en: "The ball went out the window!",           art: "kitaki" },
      { type: "q",    id: "vq_1", kn: "ಚೆಂಡು ಎಲ್ಲಿಂದ ಹೋಯಿತು — ಕಿಟಕಿನಾ, ಬಾಗಿಲಾ?",    opts: ["kitaki", "baagilu"], ans: "kitaki" },
      { type: "line", id: "v_4",  kn: "ನಾಯಿ ಚೆಂಡು ನೋಡಿತು.",                      en: "A dog saw the ball.",                     art: "naayi" },
      { type: "line", id: "v_5",  kn: "ನಾಯಿ ಓಡಿತು, ಓಡಿತು!",                      en: "The dog ran and ran!",                    art: "odu" },
      { type: "line", id: "v_6",  kn: "ನಾಯಿ ಚೆಂಡು ಬಾಯಲ್ಲಿ ತಂದಿತು!",               en: "The dog brought the ball back in its mouth!", art: "naayi" },
      { type: "q",    id: "vq_2", kn: "ಚೆಂಡು ಯಾರು ತಂದಿತು — ನಾಯಿನಾ, ಬೆಕ್ಕಾ?",       opts: ["naayi", "bekku"], ans: "naayi" },
      { type: "line", id: "v_7",  kn: "“ಒಳ್ಳೆ ನಾಯಿ!” — ಹುಡುಗ ನಕ್ಕ.",            en: "Good dog! — the boy laughed.",            art: "nagu" },
      { type: "line", id: "v_8",  kn: "ಇಬ್ಬರೂ ಚೆಂಡು ಆಡಿದರು!",                    en: "They played ball together!",              art: "chendu" },
      { type: "q",    id: "vq_3", kn: "ಅವರು ಏನು ಆಡಿದರು — ಚೆಂಡಾ, ಪುಸ್ತಕಾನಾ?",       opts: ["chendu", "pustaka"], ans: "chendu" },
    ],
  },
];

// Praise clips played on a win (audio/praise/<id>.mp3)
const PRAISE = [
  { id: "bhesh",      kn: "ಭೇಷ್!" },
  { id: "super",      kn: "ಸೂಪರ್!" },
  { id: "chennagide", kn: "ಚೆನ್ನಾಗಿದೆ!" },
  { id: "sari",       kn: "ಸರಿಯಾಗಿ ಹೇಳಿದೆ!" },
];
